config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :cars do
    resources :reservations, only: :create
  end

  resources :reservations, only: :show


  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  #get "cars", to: "cars#index"

  #get "cars/new", to: "cars#new"

  #post "cars", to: "cars#create"

  #get "cars/:id/edit", to: "cars#edit"

  #no patch

  #delete "cars/:id", to: "cars#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  validates :model, presence: true
  validates :pickup_address, presence: true
  validates :price, presence: true
  validates :description, presence: true

  has_many :reservations, dependent: :destroy

  geocoded_by :pickup_address
  after_validation :geocode, if: :will_save_change_to_pickup_address?

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true


  def self.status
    ['Approved', 'Pending', 'Declined']
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :cars, dependent: :destroy
  validates :name, :phone_number, presence: true
  validates :name, :phone_number, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  
    # For additional in app/views/devise/registrations/edit.html.erb
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

    # For additional in app/views/devise/registrations/edit.html.er
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search].present?
      @city = params[:search]
      @cars = Car.near(params[:search], 50)
    else
      @cars = Car.all
       # @cars = policy_scope(Car)
    end

  end

  def new
    @car = Car.new # car form instantiation
    authorize @car
  end

  def show
    @car = Car.find(params[:id])
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    authorize @car
    #@car = Car.new(params[:car])
    @car.user = current_user

    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
    authorize @car
  end

  def update
    @car = Car.find(params[:id])
    authorize @car
    @car.update(car_params)
    redirect_to car_path(@car)
  end

   def destroy
    @car = Car.find(params[:id])
    authorize @car
    @car.destroy

    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:model, :pickup_address, :price, :description, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:home] 
end

# this is just for commit - test

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    reservation = Reservation.new(reservation_params)
    reservation.user = current_user
    reservation.car_id = params[:car_id]
    reservation.status = 'Approved'
    days = (reservation.end_date - reservation.start_date).to_i
    reservation.total_price = days*reservation.car.price
    authorize reservation
    reservation.save

    redirect_to reservation_path(reservation)
  end

  def show
    @reservation = Reservation.find(params[:id])
    authorize @reservation
  end

  private
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<!-- **** front-part of Car owner post a car **** -->

<!-- Form generation -->
  <div class="new_forms">
    <%= form_for(@car) do |f| %>
      <div class="new_form">
        <p><i class="fas fa-car"></i><%= f.label :model %></p>
        <p><%= f.text_field :model %></p>
      </div>
      <div class="new_form">
        <p><i class="fas fa-map-marker-alt"></i><%= f.label :pickup_address %></p>
        <p><%= f.text_field :pickup_address %></p>
      </div>
      <div class="new_form">
        <p><i class="fas fa-dollar-sign"></i><%= f.label :price %></p>
        <p><%= f.text_field :price %></p>
      </div>
      <div class="new_form">
        <p><i class="fas fa-list-alt"></i><%= f.label :description %></p>
        <p><%= f.text_field :description %></p>
      </div>
      <div class="new_form new_btn">
        <p><%= f.submit %></p>
      </div>
    <% end %>
  </div>

app/views/cars/index.html.erb
<div class="container d-flex">
    <%if @cars.empty?%>
      <%= "We are sorry, in #{@city} there are not cars available"%>
    <%else %>
        <% @cars.each do |car| %>
          <div class="cards">
            <div class="card-category flex-column justify-content-center  m-3 p-3" style="background-image: linear-gradient(rgba(0,0,0,0.3)">
              <%= cl_image_tag(car.photo.key,
                    width: 400, height: 300, crop: :fill, class: "card-photo mb-3") %>
              <%= link_to car.model, car_path(car) , class: "show-button insert_car mt-3" %>
            </div>
          </div>
        <% end %>
    <% end %>
</div>

app/views/cars/new.html.erb
<!-- **** front-part of Car owner post a car **** -->

<div class="new_container text-center">
  <h1>Tell us about your car</h1>
  <p>Enter the following informations</p>

<!-- Form generation -->
  <div class="new_forms">
    <%= simple_form_for(@car) do |f| %>
      <div class="new_form">
        <p><i class="fas fa-car"></i><%= f.label :model %></p>
        <p><%= f.text_field :model %></p>
      </div>
      <div class="new_form">
        <p><i class="fas fa-map-marker-alt"></i><%= f.label :pickup_address %></p>
        <p><%= f.text_field :pickup_address %></p>
      </div>
      <div class="new_form">
        <p><i class="fas fa-dollar-sign"></i><%= f.label :price %></p>
        <p><%= f.text_field :price %></p>
      </div>
      <div class="new_form">
        <p><i class="fas fa-list-alt"></i><%= f.label :description %></p>
        <p><%= f.text_field :description %></p>
      </div>
      <div class="photo-upload">
      </div>
        <%= f.input :photo, as: :file, class: "insert_car" %>
      <!-- <div class="insert_car">-->
      <!-- </div> -->
        <p><%= f.submit "create", class: "insert_car" %></p>
    <% end %>
  </div>

</div>

app/views/cars/show.html.erb
<div id="container">
  <div id="car_pic">
    <% if @car.photo.present? %>
      <%= cl_image_tag @car.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <%= image_tag("250-testa-rossa.jpg") %>
    <% end %>
  </div>
  
  <h2 class="text-center text-justify mt-3"> <%= @car.model %> </h2>
  <p class="text-center"><strong>Description:</strong> <%= @car.description %> </p>
  <p class="text-center"><strong>Price:</strong> R$ <%= @car.price %> </p>
  <p class="text-center"><strong>Address:</strong> <%= @car.pickup_address %> </p>
  <div class="d-flex justify-content-between w-50 mx-auto">

    <% if @car.user == current_user %>

      <%= link_to "Edit", edit_car_path(@car), class: "insert_car" %>
      <%= link_to "Delete #{@car.model}",
            car_path(@car),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: "insert_car" %>

    <% else %>
      <% if current_user.present? %>
        <%= simple_form_for [@car, Reservation.new] do |form| %>
          <%= form.input :start_date %>
          <%= form.input :end_date %>
          <%= form.submit "Book now" %>
        <% end %>
      <% end %>
    <% end %>
   </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  
  <%= link_to "#", class: "navbar-brand" do %>
    <p class="logo-words">Rent n Ride</p>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">

      <% unless @home %> 
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <% end %>

      <li class="nav-item dropdown">
        <i class="fas fa-bars fa-lg" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" > </i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Sign in", "#", class: "dropdown-item" %>
          <%= link_to "Sign up", "#", class: "dropdown-item" %>
        </div>
      </li>

    </ul>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentnride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="text-center" >
  <div class="banner" style="">
    <div class="banner-content container">
      <p>Enter your location to find rental cars near you</p>
      <form action="cars" method="get" class="form-inline justify-content-center mb-5 mt-0">
        <!-- <i class="fas fa-search active" aria-hidden="true"></i> -->
        <input id="autocomplete" class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search" name="search" aria-label="Search">
        <input class="search" type="submit" value="Check all our cars">
      </form>
    </div>
  </div>
</div>


  <div class="footer">

    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>

    <div class="footer-copyright">
      This market place has been made as a project during Le Wagon's bootcamp
    </div>

  </div>

app/views/reservations/show.html.erb
<%= @reservation.total_price %>
<%= @reservation.car.model %>

app/views/shared/_footer.html.erb
  <div class="footer">

    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>

    <div class="footer-copyright">
      This market place has been made as a project during Le Wagon's bootcamp
    </div>

  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="nav-content">
    <%= link_to root_path, class: "navbar-brand" do %>
      <p class="logo-words">Rent n Ride</p>
    <% end %>

    <div class="navbar-right">
      <%= link_to "Insert a car", new_car_path, class: "insert_car mr-2" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <i class="fas fa-bars fa-lg" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" > </i>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
                <% else %>
                <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>

</div>